in_production_mode = false
application_port = 8666

[database]
host = "127.0.0.1"
port = "5432"
username = "postgres"
password = "fakepassword"
test_database_name = "test_podcast_db"
production_database_name = "podcast_db"

[s3_bucket]
access_key = "FAKEACCESSKEY" 
secret_access_key = "FAKESERCRETACCESSKEY"
region = "us-east-1"
bucket = "fake-bucket"
endpoint_url = "https://us-east-1.linodeobjects.com/" 
