CREATE TABLE channel(
  id SERIAL PRIMARY KEY,
  externalId uuid NOT NULL,
  title TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  managineEditor TEXT NOT NULL,
  generator TEXT NOT NULL,
  image_url TEXT NOT NULL,
  image_title TEXT NOT NULL,
  image_width INT NOT NULL,
  image_height INT NOT NULL,
  image_link TEXT NOT NULL,
  language TEXT NOT NULL,
  lastBuildDate TEXT NOT NULL,
  pubDate TEXT NOT NULL,
  cLink TEXT NOT NULL,
  itunes_newFeedUrl NOT NULL, 
  itunes_link (cLink),
  itunes_explicit TEXT NOT NULL,
  itunes_category (category),
  itunes_image (image_url),
  itunes_owner_name TEXT NOT NULL,
  itunes_owner_email TEXT NOT NULL,
  itunes_subtitle (description),
  googleplay_category(category),
  atem_Link(itunes_newFeedUrl),
  sy_updatePeriod TEXT NOT NULL,
  sy_updateFrequency TEXT NOT NULL
);

CREATE TABLE item(
  id uuid NOT NULL,
  PRIMARY KEY (id),
  channelId INT NOT NULL,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  contentEncoded TEXT NOT NULL,
  enlosure TEXT NOT NULL,
  iLink TEXT NOT NULL,
  pubDate TEXT NOT NULL,
  itunes_author (author),
  itunes_summary (description),
  itunes_subtitle TEXT NOT NULL,
  itunes_image TEXT NOT NULL,
  itunes_duration TEXT NOT NULL
);
